#!/usr/bin/env sh
set -e

check=
staged=
run='all'
while [ "$1" != "" ]; do
    PARAM=`echo $1 | awk -F= '{print $1}'`
    VALUE=`echo $1 | awk -F= '{print $2}'`

    case $PARAM in
        -c | --check )    check=1
                          ;;

        --staged )        staged=1
                          check=1
                          ;;

        --run )           run=$VALUE
                          ;;

        * )               echo "I don't know this option: $1"
                          exit 1
    esac
    shift
done

echo "Running $run"

if [ -z "${check}" ];  then
      echo "linting..."
else
      echo "checking..."
fi

PREFIX=
# Collect the sources to process.
if [ -n "${staged}" ]; then
      PREFIX=$(mktemp -d)/
      git diff --cached --name-only --diff-filter=ACM -z \
            | git checkout-index --prefix="$PREFIX" -z --stdin
fi

includes() { [ -z "$2" ] || { [ -z "${1##*$2*}" ] && [ -n "$1" ];};}

# This piece of work is necessary because prettier fails if the patterns
# that it receives as arguments do not match any files.
function node_check_pattern () {
      NODE_PATH=/usr/lib/node_modules/ \
            node -e 'process.exit(!require("globby").sync(process.argv.slice(1)).length);' \
                  "$@"
}

function list_python_files() {
    find "$PREFIX$LINT_FOLDER_PYTHON" \
        \( -name .tox -o -name .eggs \) -prune \
        -o \
            -type f \
            -not -path '*with_errors*' \
            -name '*.py' \
            -print
}


if [ "$run" == "all" ] || includes "$run" "docker"; then
if [ -z "$LINT_FILE_DOCKER" ]
then
      echo "\$LINT_FILE_DOCKER is not set. Skipping..."
else
      echo "LINT: DOCKER"
      hadolint $LINT_FILE_DOCKER
fi
fi

if [ "$run" == "all" ] || includes "$run" "python"; then
if [ -z "$LINT_FOLDER_PYTHON" ]
then
      echo "\$LINT_FOLDER_PYTHON is not set. Skipping..."
else
      echo "LINT: ISORT"
      if [ "${check}" ];  then
            ISORT_OPTS="--check-only --diff"
      fi
      list_python_files | xargs -r isort \
            --line-width=79 \
            --lines-after-imports=2  \
            --lines-between-types=0 \
            --trailing-comma \
            --atomic \
            --order-by-type \
            --use-parentheses \
            --multi-line=3 \
            $ISORT_OPTS \

      echo "LINT: BLACK"
      BLACK_OPTS=
      if [ -n "${check}" ];  then
            BLACK_OPTS=--check
      fi
      list_python_files | xargs -r black --line-length=79 --safe $BLACK_OPTS

      echo "LINT: AUTOFLAKE"
      if [ -z "${check}" ];  then
            list_python_files | xargs -r autoflake --in-place --remove-unused-variables
      else
            echo "not running autoflake on check"
      fi

      echo "LINT: FLAKE8"
      if [ -d "$PREFIX$LINT_FOLDER_PYTHON" ]; then
            flake8 "$PREFIX$LINT_FOLDER_PYTHON" --ignore=E501,E722,E402,W503,E203
      else
            echo "Skipping, nothing to check."
      fi
fi
fi

if [ "$run" == "all" ] || includes "$run" "scss"; then
if [ -z "$LINT_FOLDER_SCSS" ]
then
      echo "\$LINT_FOLDER_SCSS is not set. Skipping..."
elif node_check_pattern "$PREFIX$LINT_FOLDER_SCSS"; then
      echo "LINT: PRETTIER: SCSS"
      PRETTIER_OPTS=--write
      if [ -n "${check}" ];  then
            PRETTIER_OPTS=--check
      fi
      prettier \
            --no-config \
            --print-width=80 \
            --tab-width=2 \
            --arrow-parens=avoid \
            --trailing-comma=es5 \
            --single-quote \
            --jsx-bracket-same-line \
            $PRETTIER_OPTS \
            "$PREFIX$LINT_FOLDER_SCSS"
else
      echo "$PREFIX$LINT_FOLDER_SCSS did not match any files, skipping..."
fi
fi

if [ "$run" == "all" ] || includes "$run" "js"; then
if [ -z "$LINT_FOLDER_JS" ]
then
      echo "\$LINT_FOLDER_JS is not set. Skipping..."
elif node_check_pattern "$PREFIX$LINT_FOLDER_JS"; then
      echo "LINT: PRETTIER: JS"
      PRETTIER_OPTS=--write
      if [ -n "${check}" ];  then
            PRETTIER_OPTS=--check
      fi
      prettier \
            --no-config \
            --print-width=80 \
            --tab-width=2 \
            --arrow-parens=avoid \
            --trailing-comma=es5 \
            --single-quote \
            --jsx-bracket-same-line \
            $PRETTIER_OPTS \
            "$PREFIX$LINT_FOLDER_JS"
else
      echo "$PREFIX$LINT_FOLDER_JS did not match any files, skipping..."
fi
fi
